name: delivault
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'


# PACKAGES
dependencies:
  flutter:
    sdk: flutter
  
  # icons
  iconsax_flutter: ^1.0.0
  cupertino_icons: ^1.0.2
  
  # state management
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # local assets
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/

  # local fonts
  # fonts:
  #   - 
